spring:
  application:
    name: atomix-cafeteria

  # H2 In-memory database for testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration for H2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Flyway Configuration - disabled for H2
  flyway:
    enabled: false

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /api/v1

# Logging Configuration
logging:
  level:
    com.atomix.cafeteria: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG 