spring:
  application:
    name: atomix-cafeteria
  
  # H2 Database - File based for production
  datasource:
    url: jdbc:h2:file:./data/atomix_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ${DB_PASSWORD:prod_password_2024}
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: false  # Disable in production for security
      
  jpa:
    hibernate:
      ddl-auto: update  # Use update instead of create-drop for production
    show-sql: false    # Disable SQL logging in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        use_sql_comments: false
        
  flyway:
    enabled: false

# Server Configuration
server:
  port: ${PORT:8080}  # Use PORT environment variable or default to 8080
  servlet:
    context-path: /api/v1

# Security Configuration
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,https://your-frontend-domain.com}

# Logging Configuration
logging:
  level:
    root: INFO
    com.atomix.cafeteria: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 