name: Build and deploy JAR app to Azure Web App - CTS-VibeAppea71003-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Debug - List built artifacts
        working-directory: backend
        run: |
          echo "Contents of target directory:"
          ls -la target/
          echo "JAR files found:"
          find target/ -name "*.jar" -type f

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'backend/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    environment: production
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Debug - Verify downloaded artifacts
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "JAR files found:"
          find . -name "*.jar" -type f
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CTS-VibeAppea71003-2'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}
